### ISSUE TITLE
Unexpected SBT resolution failure

### ISSUE THREAD

**Issue by MartinSnyder** [LolHens/sbt-css-compress#1]
Hi Pierre,

I'm tracking down a local build failure, and it appears to me that this library is 404'ing on Maven Central.

You can see by going here and attempting to download either the .pom or the .jar: https://search.maven.org/artifact/de.lolhens/sbt-css-compress/0.2.0/jar

Any thoughts? Am I looking at this incorrectly?

**Comment by lhns** [comment]
Hi, it seems to be still on there: https://repo1.maven.org/maven2/de/lolhens/sbt-css-compress_2.12_1.0/0.2.0/
I think the maven search just doesn't handle the sbt version suffix very well.
Edit: just pressed the close button on accident.

**Comment by MartinSnyder** [comment]
Maybe the maven search feature is broken here because of how Scala name-mangles artifacts. I'll keep hunting for the root cause.

**Comment by MartinSnyder** [comment]
Here is what I see:

> [warn] 	module not found: de.lolhens.sbt#sbt-css-compress;0.2.0
> [warn] ==== typesafe-ivy-releases: tried
> [warn]   https://repo.typesafe.com/typesafe/ivy-releases/de.lolhens.sbt/sbt-css-compress/scala_2.12/sbt_1.0/0.2.0/ivys/ivy.xml
> [warn] ==== sbt-plugin-releases: tried
> [warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/de.lolhens.sbt/sbt-css-compress/scala_2.12/sbt_1.0/0.2.0/ivys/ivy.xml
> [warn] ==== local: tried
> [warn]   /Users/martin/.ivy2/local/de.lolhens.sbt/sbt-css-compress/scala_2.12/sbt_1.0/0.2.0/ivys/ivy.xml
> [warn] ==== public: tried
> [warn]   https://repo1.maven.org/maven2/de/lolhens/sbt/sbt-css-compress_2.12_1.0/0.2.0/sbt-css-compress-0.2.0.pom
> [warn] ==== local-preloaded-ivy: tried
> [warn]   /Users/martin/.sbt/preloaded/de.lolhens.sbt/sbt-css-compress/0.2.0/ivys/ivy.xml
> [warn] ==== local-preloaded: tried
> [warn]   file:////Users/martin/.sbt/preloaded/de/lolhens/sbt/sbt-css-compress_2.12_1.0/0.2.0/sbt-css-compress-0.2.0.pom
> [warn] ==== Typesafe repository: tried
> [warn]   https://repo.typesafe.com/typesafe/releases/de/lolhens/sbt/sbt-css-compress_2.12_1.0/0.2.0/sbt-css-compress-0.2.0.pom
> [warn] ==== scalaz-bintray: tried
> [warn]   https://dl.bintray.com/scalaz/releases/de/lolhens/sbt/sbt-css-compress_2.12_1.0/0.2.0/sbt-css-compress-0.2.0.pom
> [warn] ==== bintray-lolhens-sbt-plugins: tried
> [warn]   https://dl.bintray.com/lolhens/sbt-plugins/de.lolhens.sbt/sbt-css-compress/scala_2.12/sbt_1.0/0.2.0/ivys/ivy.xml
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	::          UNRESOLVED DEPENDENCIES         ::
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	:: de.lolhens.sbt#sbt-css-compress;0.2.0: not found
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::

This used to work previously, but now it's attempting to hit:
https://repo1.maven.org/maven2/de/lolhens/sbt/sbt-css-compress_2.12_1.0/0.2.0/sbt-css-compress-0.2.0.pom
instead of:
https://repo1.maven.org/maven2/de/lolhens/sbt-css-compress_2.12_1.0/0.2.0/sbt-css-compress-0.2.0.pom

Still looking into it, thought you might be interested in what I'm looking at. If I manually insert this into my local .ivy2 cache then the rest of the build completes normally. Whatever my problem with, it's only with this one library.

**Comment by lhns** [comment]
Sbt is trying to resolve `de.lolhens.sbt#sbt-css-compress;0.2.0`.
Did you specify `de.lolhens.sbt` instead of `de.lolhens`?

I think this changed when I moved from bintray to sonatype.

**Comment by MartinSnyder** [comment]
That was it. Our plugin.sbt required these changes:
```
-addSbtPlugin("de.lolhens.sbt" % "sbt-css-compress" % "0.2.0")
+addSbtPlugin("de.lolhens" % "sbt-css-compress" % "0.2.0")
```

My original instinct was that it was related to the bintray shutdown. Sorry for not taking a closer look on my own. Hopefully this comes in searches to help others!

**Comment by MartinSnyder** [comment]
Thank you!
